### ISSUE TITLE
chroot: failed to run command ‘bash’: Exec format error

### ISSUE THREAD

**Issue by klokop** [Fornoth/spotify-connect-web#23]
root@volumio:~/spotify-connect-web-chroot# ./spotify-connect-web.sh --username a --password b
chroot: failed to run command `bash': No such file or directory

**Comment by Fornoth** [comment]
What OS/device are you using?

**Comment by klokop** [comment]
https://volumio.org on a Raspberry Pi.

**Comment by Fornoth** [comment]
Do you know if the OS is softfloat or hardfloat? and RPi 1 or RPi 2? Also, which libspotify_embedded are you using?

**Comment by djmaze** [comment]
It's probably the Rocki one because he uses the pre-built chroot script.

**Comment by isabido** [comment]
I have the same error. My hardware is RPI2 with Archlinux.

To make it work I have to run the script line by line. Entering the chroot environment. and manually run the python.

In my chroot there is no bash.

**Comment by djmaze** [comment]
Okay, I changed the script to use the full path (`/bin/bash`). Should work now.

You need to change the script accordingly or just redownload it:

```
curl -O http://spotify-connect-web.s3-website.eu-central-1.amazonaws.com/spotify-connect-web.sh
```

**Comment by isabido** [comment]
Thanks!!!! Now its Ok 😉

**Comment by klokop** [comment]
Nope, still getting the same error. On an Ubuntu/Xeon system this time.

**Comment by djmaze** [comment]
@klokop spotify-connect-web uses a spotify library from ARM-based receivers and thus works only on systems running the armel/armhf architecture, e.g. Raspberry Pi. (We should probably document that fact better.)

You could try [librespot](https://github.com/plietar/librespot) on your x86 machine instead.

**Comment by klokop** [comment]
I figured as much. Will try on Pi. thx.

**Comment by Fornoth** [comment]
I'm gonna close this for now, feel free to re-open if you're still having problems

**Comment by klokop** [comment]
Nope, is fine to close. It's all working now. Thanks!

**Comment by 1337sup3rh4x0r** [comment]
I just ran into the same issue when trying to install this on a debian x64 system.
So can this be resolved by just exchanging a binary within the chroot at some place or does it need more changes than that?

**Comment by djmaze** [comment]
@1337sup3rh4x0r This software depends on a spotify library binary which can only be found on ARM-based receiver devices. Thus it is not possible to run this on a x86/x64 system. 

You should probably try out [librespot](https://github.com/plietar/librespot) instead.

**Comment by 1337sup3rh4x0r** [comment]
Thank you for clarifying. So does the binary within spotify-connect-web need to be replaced with librespot or does librespot offer Spotify connect features and replaces spotify-connect-web as a whole?

**Comment by djmaze** [comment]
It replaces it as a whole. There already is a [sample program](https://github.com/plietar/librespot#usage) which acts as a spotify connect receiver.
